extends:
  - eslint:recommended
  - prettier

env:
  browser: true
  es2021: true

parserOptions:
  sourceType: module

ignorePatterns:
  - .github
  - dist

rules:
  curly: error
  eqeqeq: error
  object-shorthand: error
  prefer-const: error
